### PR TITLE
Modernize build

### PR DESCRIPTION
**Pull request by basil**
Depends on #286 and #287. Required for #284. Does the following:

- Incrementalize plugin (see [JEP-305](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc)).
- Updates plugin parent POM to latest version
- Updates Maven dependencies to latest versions
- Updates minimum Jenkins version per [the developer documentation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)
- Adds [plugin BOM](https://github.com/jenkinsci/bom) for easier management of plugin versions

CC @damianszczepanik

### CODE REVIEW

**Comment by basil** [comment]
Hi @damianszczepanik, friendly gentle ping. This PR is needed for the core developers to be able to move forward with [JENKINS-69988](https://issues.jenkins.io/browse/JENKINS-69988).

**Comment by damianszczepanik** [comment]
OK, based on your answer I understood that this PR is not critical for your motivation described in mentioned JIRA. I thought that this is only for incremental release for PR.

I see that this is critical. which change does reflect to JIRA? Is is about plugin version 4.47 ?

**Comment by basil** [comment]
Updating the Jenkins baseline to a more recent version is needed to be able to depend on the HttpClient 3.x plugin. That in turn requires updating the parent POM to a recent version. That in turn cascades to the other dependency updates in this PR.

**Comment by damianszczepanik** [comment]
Roger that. I'm owning a few more plugins, should I change/update them somehow ?

**Comment by basil** [comment]
> Roger that. I'm owning a few more plugins, should I change/update them somehow ?

Not unless they are on [this list](https://docs.google.com/spreadsheets/d/1jXTJmHLVg6HpWA_-8vkcmL0Q005EKqIkykPgRLsj9K0/edit#gid=0).

**Pull request merged**
