### PR TITLE
Migrate from Commons HttpClient 3.x to HttpComponents Client 4.x

### PR DESCRIPTION
**Pull request by basil**
Alternative to #293. The critical change that my previous PRs have been leading up to: stop depending on Commons HttpClient 3.x from core so that HttpClient 3.x can be removed from core. To implement this, there are two options:

- Depend on Commons HttpClient 3.x via a plugin-to-plugin dependency on `commons-httpclient3-api` (#293)
- Depend on Commons HttpClient 4.x via a plugin-to-plugin dependency on `apache-httpcomponents-client-4-api` (this PR)

This PR is greater risk because it is upgrading the dependency from version 3.x to 4.x. Some testing would be appreciated. The existing unit test had to be deleted, because there is no way to implement it with HttpClient 4.x, which does not expose proxy information from `DefaultHttpClient`.

CC @damianszczepanik

### CODE REVIEW

**Comment by basil** [comment]
I will leave this PR open, but I am not advocating strongly for it to be merged in a short time frame. This migration is good for the long-term health of this plugin, but it needs end-to-end functional testing to ensure that no bugs are introduced, and I am unable to provide this testing, especially because I am not an actual user of this plugin. I would welcome it if someone else could eventually test and merge this PR, but that is not blocking me in any way.

**Comment by basil** [comment]
Any update on this PR?

**Comment by damianszczepanik** [comment]
Tested against all jobs which I have for testing - works fine

**Comment by basil** [comment]
Thanks!

**Pull request merged**
