### PR TITLE
replace run number with custom run name instead of job name

### PR DESCRIPTION
**Pull request by hurzelchen**
Instead of replacing the Job Name on a card when a custom build run name is set, the run number will be replaced.

### CODE REVIEW

**Comment by casz** [comment]
seems reasonable.
Your commit is not associated with your github account if you want the credit 🤭

https://github.com/jenkinsci/office-365-connector-plugin/commit/3f78abe5a08d8b1ca03a9e27c528fc19b054920d.patch outch that git username 😅

https://help.github.com/articles/setting-your-username-in-git/
https://help.github.com/articles/setting-your-commit-email-address-in-git/
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

**Comment by hurzelchen** [comment]
Yeah, the "joy" of having a German UTF-8 name ;-)

And my machine has to have to have multiple git identities... but I thought I've never set one in the global config.

Would you actually mind closing that pull request and I'll resubmit it with the correct user and email?

**Comment by casz** [comment]
you can just force push?

**Comment by hurzelchen** [comment]
Oh yeah... looks like I can. Would not have expected that to work, tbh.

**Comment by damianszczepanik** [comment]
Merged,
Thanks for the small change and the test!

**Comment by casz** [comment]
@damianszczepanik thanks for taking over the project 🙌

**Pull request merged**
