### PR TITLE
Use gson api plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Use gson api plugin instead of bundle jar directly

### Testing done

Automated tests

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by damianszczepanik** [comment]
@jonesbusy this change causes error when releasing new version:
```
[INFO] 3/3 perform:run-perform-goals
[INFO] Invoking perform goals in directory office-365-connector-plugin\target\checkout
[INFO] Executing goals 'deploy'...
[INFO] [INFO] Scanning for projects...
[INFO] Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/io/jenkins/tools/bom/bom-2.401.x/2747.v0842b_c87549e/bom-2.401.x-2747.v0842b_c87549e.pom
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/io/jenkins/tools/bom/bom-2.401.x/2747.v0842b_c87549e/bom-2.401.x-2747.v0842b_c87549e.pom
[INFO] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[INFO] [ERROR] Non-resolvable import POM: Could not find artifact io.jenkins.tools.bom:bom-2.401.x:pom:2747.v0842b_c87549e in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) @ line 38, column 16
[INFO] [ERROR] 'dependencies.dependency.version' for io.jenkins.plugins:gson-api:jar is missing. @ line 67, column 21
[INFO] [ERROR] 'dependencies.dependency.version' for org.jenkins-ci.plugins:token-macro:jar is missing. @ line 71, column 21
[INFO] [ERROR] 'dependencies.dependency.version' for org.jenkins-ci.plugins:display-url-api:jar is missing. @ line 75, column 21
[INFO] [ERROR] 'dependencies.dependency.version' for org.jenkins-ci.plugins:scm-api:jar is missing. @ line 79, column 21
[INFO] [ERROR] 'dependencies.dependency.version' for org.jenkins-ci.plugins.workflow:workflow-step-api:jar is missing. @ line 83, column 21
[INFO] [ERROR] 'dependencies.dependency.version' for org.jenkins-ci.plugins:apache-httpcomponents-client-4-api:jar is missing. @ line 87, column 21
[INFO]  @
[INFO] [ERROR] The build could not read 1 project -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR]   The project org.jenkins-ci.plugins:Office-365-Connector:4.21.0 (office-365-connector-plugin\target\checkout\pom.xml) has 7 errors
[INFO] [ERROR]     Non-resolvable import POM: Could not find artifact io.jenkins.tools.bom:bom-2.401.x:pom:2747.v0842b_c87549e in repo.jenkins-ci.org(https://repo.jenkins-ci.org/public/) @ line 38, column 16 -> [Help 2]
[INFO] [ERROR]     'dependencies.dependency.version' for io.jenkins.plugins:gson-api:jar is missing. @ line 67, column 21
[INFO] [ERROR]     'dependencies.dependency.version' for org.jenkins-ci.plugins:token-macro:jar is missing. @ line 71, column 21
[INFO] [ERROR]     'dependencies.dependency.version' for org.jenkins-ci.plugins:display-url-api:jar is missing. @ line 75, column 21
[INFO] [ERROR]     'dependencies.dependency.version' for org.jenkins-ci.plugins:scm-api:jar is missing. @ line 79, column 21
[INFO] [ERROR]     'dependencies.dependency.version' for org.jenkins-ci.plugins.workflow:workflow-step-api:jar is missing. @ line 83, column 21
[INFO] [ERROR]     'dependencies.dependency.version' for org.jenkins-ci.plugins:apache-httpcomponents-client-4-api:jar is missing. @ line 87, column 2
```

can you help me with this issue?

**Comment by jonesbusy** [comment]
Many plugin depending on gson api where released correctly in the past weeks. I'm not very familiar to manual release process to be honest (all the one I maintain are using CD)

**Comment by jonesbusy** [comment]
By the way bom version doesn't match the one of this PR.

Also from what I see is that the 2.401 line was removed from bom (due to incoming 2.440). So probably better to start already to depends on 2.414

**Comment by damianszczepanik** [comment]
I can switch to another bom but problem I mention occurs when deploying new release but works fine for `mvn verify`

**Pull request merged**
