### PR TITLE
Add support for start and completed card

### PR DESCRIPTION
**Pull request by casz**
This example use case

https://github.com/jenkinsci/office-365-connector-plugin/commit/4829647646140da33e8477625d36915238d6e732

specifying status: "started" to get the regular started card
and then specifying only webhook you will get the completed card.

I would advice against having the work folder in git... +140 files when I changed the Jenkins version to 2.x because of pipeline job. I can of course remove the commit if you need me to.

```
pipeline {
  agent any
  environment {
    HOOK = "https://outlook.office.com/webhook/x"
  }
  stages {
    stage("build") {
      steps {
        office365ConnectorSend status: "Started", webhookUrl: "${env.HOOK}"
      }
    }
  }
  post {
    success {
      office365ConnectorSend webhookUrl: "${env.HOOK}"
    }
    failure {
      office365ConnectorSend webhookUrl: "${env.HOOK}"
    }
  }
}
```

### CODE REVIEW

**Comment by casz** [comment]
Current status for pipeline:
image

**Comment by casz** [comment]
@outconn a review would be nice?

**Comment by drmmr763** [comment]
👍 need this too! Any chance of merging for a release?

**Comment by Kolky** [comment]
Any chance for this to be in a new release soon?

**Comment by Kolky** [comment]
@casz Could you make a hpi? So we can use your version already?

**Comment by casz** [comment]
Closing in favor of separate PR

**Comment by casz** [comment]
See #8

**Pull request closed without merging**
