### PR TITLE
Moves Macro class into model package

### PR DESCRIPTION
**Pull request by damianszczepanik**
It should be already there. My bad.

### CODE REVIEW

**Comment by damianszczepanik** [comment]
@SrhebbarMicrosoft  please collect PR as they were submitted so I can handle renaming in jelly files.

**Comment by SrhebbarMicrosoft** [comment]
Wow. Lot of changes... Just give me some time, I'll take a look and merge....

**Comment by damianszczepanik** [comment]
@SrhebbarMicrosoft any plan for release? I want to collect feedback from the team

**Comment by SrhebbarMicrosoft** [comment]
Can you please fix dateToString_ReturnsDateAsString UT. As this is failing, I am not able to make a release. I don't want to comment this and release.

**Comment by damianszczepanik** [comment]
I wish but it works locally. Can you provide stacktrace as I guess there is still something wrong with locale or timezone.  :(

**Comment by SrhebbarMicrosoft** [comment]
jenkins.plugins.office365connector.TimeUtilsTest.dateToString_ReturnsDateAsString(jenkins.plugins.office365connector.TimeUtilsTest)
  Run 1: TimeUtilsTest.dateToString_ReturnsDateAsString:23 
Expecting:
 <"2017-09-30 02:05:41 IST">
to start with:
 <"2017-09-29">

  Run 2: TimeUtilsTest.dateToString_ReturnsDateAsString:23 
Expecting:
 <"2017-09-30 02:05:41 IST">
to start with:
 <"2017-09-29">

  Run 3: TimeUtilsTest.dateToString_ReturnsDateAsString:23 
Expecting:
 <"2017-09-30 02:05:41 IST">
to start with:
 <"2017-09-29">

  Run 4: TimeUtilsTest.dateToString_ReturnsDateAsString:23 
Expecting:
 <"2017-09-30 02:05:41 IST">
to start with:
 <"2017-09-29">

  Run 5: TimeUtilsTest.dateToString_ReturnsDateAsString:23 
Expecting:
 <"2017-09-30 02:05:41 IST">
to start with:
 <"2017-09-29">

**Comment by damianszczepanik** [comment]
PR sent - logs were very helpful!

**Pull request merged**
