### PR TITLE
perform variable expansion on webhook URLs

### PR DESCRIPTION
**Pull request by carej**

### CODE REVIEW

**Comment by drwoods** [comment]
+1 as this allows you to pass the URL as a build parameter to other jobs

**Comment by casz** [comment]
@SrhebbarMicrosoft if you accept #6 this one should be able to be merged 👍

**Comment by SrhebbarMicrosoft** [comment]
As #6 is merged, am closing this.

**Comment by casz** [comment]
same thing, #6 was only meant to fix line endings.

It did not include this PR, and this PR is quite valid.

**Comment by SrhebbarMicrosoft** [comment]
@carej Can you please provide me the issue this PR is solving... I will just copy paste this in the release notes...

**Comment by casz** [comment]
This PR allows one to have the webhook set as 

- Allow webhook parameter to be expanded

So for a build you can define your webhook as `$webhook`
And have the the ability to expand the `$webhook` value to an actual URL either by node environment variables, build variables, build parameters and etc.

**Pull request merged**
