### PR TITLE
Fixed Card themeColor attribute, added some color to the Build-finished cards

### PR DESCRIPTION
**Pull request by evertonmc**
https://docs.microsoft.com/en-us/outlook/actionable-messages/card-reference#card-fields

### CODE REVIEW

**Comment by drmmr763** [comment]
👍 could use this right now

**Comment by casz** [comment]
@SrhebbarMicrosoft if you accept #6 this one should be able to be merged 👍

**Comment by casz** [comment]
See, no merge conflicts 👍

**Comment by casz** [comment]
@SrhebbarMicrosoft if you close and reopen PRs, the ci.jenkins.io should restart the build (continuous-integration/jenkins/pr-merge) to make it go green 👍

**Comment by SrhebbarMicrosoft** [comment]
As  #6 is merged, am closing this.

**Comment by evertonmc** [comment]
This one is not merged yet

**Comment by casz** [comment]
what? #6 was only meant to fix line endings.

This PR adds colors to the card.
See the effect in these screenshots:

image
image
image

**Comment by SrhebbarMicrosoft** [comment]
@evertonmc sorry for the confusion... I read the comment wrong. After Jenkins perform the checks, I'll merge... Thanks for the screenshot and comments... You've reduced my work... :)

**Pull request merged**
